### ISSUE TITLE
Not possible to download models

### ISSUE THREAD

**Issue by MadisLemsalu** [beingjoey/pytorch_openpose_body_25#1]
Hey it's not possible to download the models without downloading baidu auxillary download methods. Is it possible to use some other platform which can be accessed from the EU?

**Comment by MadisLemsalu** [comment]
Apparentyl baidu requires chinese ID and phone number for the download

**Comment by beingjoey** [comment]
sorry , I can not use google driver in china

**Comment by Usama3059** [comment]
Please send by using dropbox

**Comment by culurciello** [comment]
Hi, I am also not able... has anyone gotten ahold of this? Or know how to convert the caffe model?

**Comment by beingjoey** [comment]
google driver added.
