### ISSUE TITLE
Missing Presentation of Hand Fingers in (body_25) Result

### ISSUE THREAD

**Issue by MosbehBarhoumiRAI** [beingjoey/pytorch_openpose_body_25#4]
Thank you for sharing this excellent work. I have a question regarding the (body_25) result: I noticed that the presentation for the right and left hand fingers is missing. Is there a way to adjust the parameters to include them in the drawing?
This is the result of the :
![00891_00_rendered](https://user-images.githubusercontent.com/78423450/223971136-d41cd7b8-739f-44c3-afe4-9d884e43f271.png)
This is what I want to get : 
![00891_00_rendered](https://user-images.githubusercontent.com/78423450/223972592-e80b2d8c-d00d-4b28-ae55-590d15199fbc.png)

**Comment by DepressedSage** [comment]
Hi @MosbehBarhoumi I wanted to ask, how were you able to resolve the issue?

**Comment by MosbehBarhoumiRAI** [comment]
@DepressedSage I have employed two GitHub repositories for my that. The first one, available at https://github.com/beingjoey/pytorch_openpose_body_25, was used to extract body key-points. The second repository, found at https://github.com/Hzzone/pytorch-openpose, was utilized to detect hand key-points. Ultimately, the task involved merging the results obtained from these two sources.

**Comment by DepressedSage** [comment]
Oh! I had come to the same conclusion for that! But I was hoping for any other option. 
Thank you so much for your prompt answer. :)

**Comment by KilluaZHou** [comment]
Hello, I'd like to ask how you adjusted the colors and line proportions from the first image to the second one?

**Comment by MosbehBarhoumiRAI** [comment]
@KilluaZHou  Hi! Feel free to check out my GitHub repository for VITON preprocessing: [VITON-PRE-PROCESSING](https://github.com/MosbehBarhoumi/VITON-PRE-PROCESSING). The colors don't actually matter—if you're concerned about them, you just need to re-color each part using the corresponding colors, which can be found in the OpenPose GitHub repository.
